version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: reservas_db
    environment:
      POSTGRES_DB: reservas_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: DB_Gal_Reservas2025
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./seeds.sql:/docker-entrypoint-initdb.d/02-seeds.sql
    restart: unless-stopped

volumes:
  postgres_data:
